### PR TITLE
Issue 3 skip record level selection

### LINKED ISSUE #3: Skip the level selection step
### Description ###

The step where you choose the JSON import level can be skipped, it's always the same.
The column name should come from the JSON fields name of the first record.

So the project name and tags could/should be asked the step before.

### Screenshot ###
image

### PR DESCRIPTION
**Pull request by WaltonG**
Fixes #3

Changes proposed in this pull request:

- Skip the record level selection and display all rows and columns of the received data on the preview page.

### CODE REVIEW

**Comment by WaltonG** [comment]
@antoine2711 @wetneb This PR produces OutOfMemoryError when creating a project. At first it was caused by https://github.com/OpenRefine/SparqlExtension/blob/869b9cfcc0d8e952c199dce4c72e951d9b0b75d4/src/main/java/org/openrefine/extensions/sparql/utils/SPARQLImportingController.java#L312

I changed the declaration to `List<Object> rowOfCells = null;` and added values to the list using `rowOfCells = Collections.singletonList(jsonRows.get(index++))` This moved the cause to line and I applied the same solution

https://github.com/OpenRefine/SparqlExtension/blob/869b9cfcc0d8e952c199dce4c72e951d9b0b75d4/src/main/java/org/openrefine/extensions/sparql/utils/SPARQLImportingController.java#L308

The cause was then moved to line https://github.com/OpenRefine/SparqlExtension/blob/869b9cfcc0d8e952c199dce4c72e951d9b0b75d4/src/main/java/org/openrefine/extensions/sparql/utils/SPARQLImportingController.java#L217

I commented out the line and now the current error is ` Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "OkHttp TaskRunner"
Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "pool-2-thread-2"` 

The code was succesfull in fetching the preview data and displaying it but on using the same code to create a project it results to OutOfMemoryError

**Comment by wetneb** [comment]
@antoine2711 can I leave this to you first? Ping me if you are stuck.

**Comment by antoine2711** [comment]
> @antoine2711 can I leave this to you first? Ping me if you are stuck.

Sure. I was already looking into it. 

Regards, Antoine

**Comment by WaltonG** [comment]
Just realised that in the database extension two classes that implement TableDataReader were used. One for the  preview data and the other for the whole result set that creates the project. I will implement that and see the outcome

**Comment by antoine2711** [comment]
> Just realised that in the database extension two classes that implement TableDataReader were used. One for the preview data and the other for the whole result set that creates the project. I will implement that and see the outcome

K. You might also have seen this:
image

```
java.lang.Error: Unresolved compilation problem: 
	SPARQLQueryResultPreviewReader cannot be resolved to a type
```

Regards, Antoine

**Comment by WaltonG** [comment]
The error still persists even after implementing create project TableDataReader in a separate java class. Using a small dataset of less that 50 rows gave me a false postive that the error is fixed hence the merging.

**Pull request merged**
